// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";

const fallbackDataDir = path.resolve(process.cwd(), "data");
const databaseUrl = process.env["DATABASE_URL"]?.trim() || `file:${path.join(fallbackDataDir, "homevault.db")}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
